In [2]:
import sys
sys.path

['/Users/heng/Desktop/eco_programe/eco_pro',
 '/Users/heng/anaconda3/lib/python311.zip',
 '/Users/heng/anaconda3/lib/python3.11',
 '/Users/heng/anaconda3/lib/python3.11/lib-dynload',
 '',
 '/Users/heng/anaconda3/lib/python3.11/site-packages',
 '/Users/heng/anaconda3/lib/python3.11/site-packages/aeosa',
 '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages',
 '/Users/heng/Desktop/eco_programe/eco_pro']

In [3]:
import os
os.getcwd()

'/Users/heng/Desktop/eco_programe/eco_pro'

In [3]:
from gamepy.game import Game

# prisioner's dilemma
game = Game(
    ["Alice", "Bob"],
    [["C","D"],["C","D"]],
    {("C","C"):(3,3), ("C","D"):(0,5), 
     ("D","C"):(5,0), ("D","D"):(1,1)}
)
Alice, Bob = game.players

In [12]:
Game.payoff(Alice, Bob) 

TypeError: Game.payoff() takes 1 positional argument but 2 were given

In [ ]:
game = Game()
game_id = "g-1"

selected_game = game_menu[game_id]   
game = Game(
    selected_game["players"],
    selected_game["actions"],
    selected_game["payoffs"]


)

In [1]:
from gamepy.gamemenu.menu import menus

class Games:
    menus = menus
    def __init__(self):
        pass

ImportError: cannot import name 'menus' from 'gamepy.gamemenu.menu' (/Users/heng/Desktop/eco_programe/eco_pro/gamepy/gamemenu/menu.py)

In [ ]:
from gamepy.gamemenu.menu import menus

In [13]:
from gamepy.game import Game

# prisioner's dilemma
game = Game(
    ["player1", "player2"],
    [["C","D"],["C","D"]],
    {("C","C"):(3,3), ("C","D"):(0,5), 
     ("D","C"):(5,0), ("D","D"):(1,1)}
)
Alice, Bob = game.players

game2 = Game(
    ["player1", "player2"],
    [["P","S","R"],["P","S","R"]],
    {("P","P"):(0,0), ("P","S"):(-1,1), ("P","R"):(1,-1),
     ("S","P"):(1,-1), ("S","S"):(0,0), ("S","R"):(-1,1),
     ("R","P"):(-1,1), ("R","S"):(1,-1), ("R","R"):(0,0)}
)
Alice2, Bob2 = game2.players

In [14]:
Alice2, Bob2

(<gamepy.game.Player at 0x1263d7650>, <gamepy.game.Player at 0x1263d7810>)

In [1]:
from gamepy.game import Game
from gamepy.gamemenu.menu import menus

# a prototype
class Games:
    menus = menus
    def __init__(self):
        pass

In [ ]:

SAMPLE_SPREADSHEET_ID= "https://docs.google.com/spreadsheets/d/1NskFAHyHtZPZreSRv9rSncCn3JukWV2g9g4ya3my-yc/edit?usp=sharing"
SAMPLE_RANGE_NAME = "A1:G"

In [ ]:
import os.path
os.getcwd()

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# If modifying these scopes, delete the file token.json.
SCOPES = ["https://www.googleapis.com/auth/spreadsheets.readonly"]

# The ID and range of a sample spreadsheet.
SAMPLE_SPREADSHEET_ID = "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
SAMPLE_RANGE_NAME = "Class Data!A2:E"


def main():
  """Shows basic usage of the Sheets API.
  Prints values from a sample spreadsheet.
  """
  creds = None
  # The file token.json stores the user's access and refresh tokens, and is
  # created automatically when the authorization flow completes for the first
  # time.
  if os.path.exists("token.json"):
    creds = Credentials.from_authorized_user_file("token.json", SCOPES)
  # If there are no (valid) credentials available, let the user log in.
  if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
      creds.refresh(Request())
    else:
      flow = InstalledAppFlow.from_client_secrets_file(
          "credentials.json", SCOPES
      )
      creds = flow.run_local_server(port=0)
    # Save the credentials for the next run
    with open("token.json", "w") as token:
      token.write(creds.to_json())

  try:
    service = build("sheets", "v4", credentials=creds)

    # Call the Sheets API
    sheet = service.spreadsheets()
    result = (
        sheet.values()
        .get(spreadsheetId=SAMPLE_SPREADSHEET_ID, range=SAMPLE_RANGE_NAME)
        .execute()
    )
    values = result.get("values", [])

    if not values:
      print("No data found.")
      return

    print("Name, Major:")
    for row in values:
      # Print columns A and E, which correspond to indices 0 and 4.
      print(f"{row[0]}, {row[4]}")
  except HttpError as err:
    print(err)


if __name__ == "__main__":
  main()
### 

###如果有要改scope的話，要刪除token.json  重新跑一次

In [2]:
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# If modifying these scopes, delete the file token.json.
SCOPES = ["https://www.googleapis.com/auth/spreadsheets.readonly"]

# The ID and range of your spreadsheet.
SAMPLE_SPREADSHEET_ID = "1NskFAHyHtZPZreSRv9rSncCn3JukWV2g9g4ya3my-yc"
SAMPLE_RANGE_NAME = "Sheet1!A2:E5"  # 假設您想要從 'Sheet1' 的 A2 到 E5 讀取數據



def main():
  """Shows basic usage of the Sheets API.
  Prints values from a sample spreadsheet.
  """
  creds = None
  # The file token.json stores the user's access and refresh tokens, and is
  # created automatically when the authorization flow completes for the first
  # time.
  if os.path.exists("token.json"):
    creds = Credentials.from_authorized_user_file("token.json", SCOPES)
  # If there are no (valid) credentials available, let the user log in.
  if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
      creds.refresh(Request())
    else:
      flow = InstalledAppFlow.from_client_secrets_file(
          "credentials.json", SCOPES
      )
      creds = flow.run_local_server(port=0)
    # Save the credentials for the next run
    with open("token.json", "w") as token:
      token.write(creds.to_json())

  try:
    service = build("sheets", "v4", credentials=creds)

    # Call the Sheets API
    sheet = service.spreadsheets()
    result = (
        sheet.values()
        .get(spreadsheetId=SAMPLE_SPREADSHEET_ID, range=SAMPLE_RANGE_NAME)
        .execute()
    )
    values = result.get("values", [])
    print(values)
    if not values:
      print("No data found.")
      return

    print("Name, Major:")
    for row in values:
      # Print columns A and E, which correspond to indices 0 and 4.
      print(f"{row[0]}, {row[4]}")
  except HttpError as err:
    print(err)


In [3]:

##beta and alpha 是一開始就要設定參intialize    
class Consumer_LogUtility:
    def __init__(self, beta):
        self.beta = beta
    def foc_c(self, knext: float, w: float, R: float): # (23.6b)
        """
        First order condition of the consumer's problem
        (knext, w, R)
        """
        return knext - (self.beta/(1+self.beta))*w

class Producer_cobbDouglas:
    def __init__(self, alpha):
        self.alpha = alpha
    def foc_l(self, k, w, l=1): # (23.9)
        """ 
        FOC with respect to labor
        (k, l, w)
        """
        return (1-self.alpha)*(k/l)**self.alpha - w
    def foc_k(self, k, R, l=1): # (23.9)
        """
        FOC with respect to capital
        (k, l, R)
        """
        return self.alpha*(l/k)**(1-self.alpha) - R

In [13]:
consumer_logutility = Consumer_LogUtility(beta=0.9)
consumer_logutility.foc_c(knext=1, w=1, R=1)

0.5263157894736842

In [14]:
class OLGMarket:
    def __init__(self, consumer, producer, k0):
        self.consumer = consumer # composite 1
        self.producer = producer # composite 2
        self.k0 = k0
        self.k = k0
        self.equilibrium_dynamics = [[k0, None, None]]
    def generate_onePeriod_equilibrium(self):
        """
        return a tuple of (knext, w, R)
        and track the dynamics in self.equilibrium_dynamics
        """ # docstring: documentation string
        
        alpha = self.producer.alpha
        beta = self.consumer.beta

        w = (1-alpha)*self.k**alpha
        R = alpha*(self.k)**(alpha-1)
        knext = (beta/(1+beta))*w

        # keep track of the dynamics
        self.equilibrium_dynamics[len(self.equilibrium_dynamics)-1][1] = w
        self.equilibrium_dynamics[len(self.equilibrium_dynamics)-1][2] = R
        self.equilibrium_dynamics.append([knext, None, None])

        # set the market time to the next period
        self.k = knext
        return (knext, w, R)
    
    def clear_equilibrium_dynamics(self):
        self.equilibrium_dynamics = [[self.k0, None, None]]
        self.k = self.k0

In [22]:
olg=OLGMarket( Consumer_LogUtility(beta=0.2), Producer_cobbDouglas(alpha=0.3), k0=0.8)
olg.generate_onePeriod_equilibrium()
olg.clear_equilibrium_dynamics()

In [9]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def bark(self):
        return f"{self.name} says woof!"

# 創建 Dog 類的實例
my_dog = Dog(name="Buddy", age=3)

# 使用實例的屬性和方法
print(f"My dog's name is {my_dog.name} and he is {my_dog.age} years old.")
print(my_dog.bark())


My dog's name is Buddy and he is 3 years old.
Buddy says woof!


Packing is to pack all non-key-value-pair argument values into a tuple.

In [15]:
import numpy as np  

class AR_Model:
    def __init__(self, *phi, epsilon, Y0):
        self.phi = np.array(phi)
        self.epsilon = epsilon
        self.Y0 = np.array(Y0)
        self.memory = np.array([])
        self.YPast = np.array(self.Y0)
    ## helper functions  
    def simulate_onePeriod(ar, eps):
        y_onePeriod_ahead = ar.phi@ar.YPast + eps
        ar.YPast = np.append(y_onePeriod_ahead, ar.YPast[:-1])
        ar.memory = np.append(ar.memory, y_onePeriod_ahead)
    def Epsilon(mu , sigma):
        def draw (size):
         return np.random.normal(mu, sigma, size)
        return draw


In [23]:
import numpy as np  

class AR_Model:
    def __init__(self, *phi, epsilon, Y0):
        self.phi = np.array(phi)
        self.epsilon = epsilon
        self.Y0 = np.array(Y0)
        self.memory = np.array([])
        self.YPast = np.array(self.Y0)
    ## helper functions  
    def simulate_onePeriod(ar, eps):
       y_onePeriod_ahead = ar.phi@ar.YPast + eps
       ar.YPast = np.append(y_onePeriod_ahead, ar.YPast[:-1])
       ar.memory = np.append(ar.memory, y_onePeriod_ahead)
    
    def simulate_NPeriods(ar, N):
        for i in range(N):
            eps = ar.epsilon(i)
            ar.simulate_onePeriod(eps)

    def Epsilon(mu , sigma):
        def draw (size):
         return np.random.normal(mu, sigma, size)
        return draw

In [24]:
ar = AR_Model(0.5,-0.2, epsilon=AR_Model.Epsilon(0, 1), Y0=[0,0])
ar.simulate_NPeriods(100)
ar.memory


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [16]:
epsilon = AR_Model.Epsilon(mu=0, sigma=1)
ar = AR_Model(0.5, 0.2, epsilon=epsilon, Y0=[0, 0])
ar.epsilon(10)

array([ 0.44885203,  1.38230748, -0.39413115,  0.70814695,  1.98730504,
       -0.98341328,  0.60315389, -0.74407569, -0.65955392, -0.88640734])

In [19]:
ar.simulate_onePeriod(ar.epsilon(1))


In [21]:

print(ar.YPast) , 
print(ar.memory)    

[-1.04276969 -1.41586447]
[-1.7759491  -1.41586447 -1.04276969]


In [10]:
import numpy as np  

class AR:
    def __init__(self, *phi, epsilon, Y0):
        self.phi = np.array(phi)
        self.epsilon = epsilon
        self.Y0 = np.array(Y0)
        self.memory = np.array([])
        self.YPast = np.array(self.Y0)

In [12]:
def simulate_onePeriod(ar, eps):
    # Simulate one period of ar process
    y_onePeriod_ahead = ar.phi@ar.YPast + eps

    # Update YPast
    ar.YPast = np.append(y_onePeriod_ahead, ar.YPast[:-1])

    ## append the new element to the memory
    ar.memory = np.append(ar.memory, y_onePeriod_ahead)

eps = ar.epsilon(1)
ar = AR(0.8, -0.35, epsilon=epsilon, Y0=[0,0])
ar.memory

array([], dtype=float64)

In [2]:
np.random.seed(123)
def Epsilon(mu , sigma):
    def draw (size):
         return np.random.normal(mu, sigma, size)
    return draw

epsilon = Epsilon(mu=0, sigma=1)
epsilon(10)

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [4]:
ar = AR_Model(0.5, 0.5, epsilon=epsilon, y0=[0, 0])  
ar.memory
ar.ypast
ar.phi

(0.5, 0.5)

In [47]:
ar.epsilon

<function __main__.Epsilon.<locals>.draw(size)>

In [54]:
ar.epsilon(10)

array([-0.77270871,  0.79486267,  0.31427199, -1.32626546,  1.41729905,
        0.80723653,  0.04549008, -0.23309206, -1.19830114,  0.19952407])

In [55]:
def test(*args, epsilon):
    print(args)
    print(epsilon)

test(1,2,3, epsilon="Hi")

(1, 2, 3)
Hi


In [16]:
eps  = ar.epsilon(1)
y_oneperiod = ar.phi[0]*ar.ypast[-1] + ar.phi[1]*ar.ypast[-2] + eps
ar.ypast = np.append(ar.ypast, y_oneperiod) 
y_oneperiod , ar.ypast

(array([4.03951843]),
 array([ 0.        ,  0.        , -0.67888615, -0.43415204,  0.93487053,
        -0.38854276, -0.17081807, -0.71403169,  1.7635052 ,  2.71152284,
         3.24156792,  3.36273178,  4.03951843]))

In [64]:
y_oneperiod = ar.phi @ ar.ypast[-2:] + eps
y_oneperiod
## -2: 代表最後兩個 

array([0.20926589])

In [5]:
ar.ypast[-2:]

array([0, 0])

In [56]:
import sympy as sp

# Define the CES utility function
def CES_utility(x, alpha, rho):
    """
    Compute the CES utility function for a given set of goods `x`, share parameters `alpha`, 
    and elasticity of substitution `rho`.
    
    :param x: List of quantities of goods
    :param alpha: List of share parameters for goods
    :param rho: Elasticity of substitution
    :return: Computed utility
    """
    # Ensure that the number of goods and share parameters match
    if len(x) != len(alpha):
        raise ValueError("The number of goods and number of share parameters must be equal.")
    
    # Calculate the utility
    utility = sum(alpha_i * x_i**rho for alpha_i, x_i in zip(alpha, x))**(1/rho)
    return utility

# Define the parameters for the two examples
alpha_1 = [0.3, 0.4, 0.3]
rho_1 = 2
goods_1 = [2, 4, 5]

alpha_2 = [0.2, 0.2, 0.3, 0.3]
rho_2 = 2
goods_2 = [1, 2, 2, 1]

# Compute the utility for the two examples
utility_1 = CES_utility(goods_1, alpha_1, rho_1)
utility_2 = CES_utility(goods_2, alpha_2, rho_2)

utility_1, utility_2


(3.88587184554509, 1.5811388300841898)