In [2]:
import numpy as np
from numpy.linalg import inv
class Demand:
    def __init__(self, D, h):
        self.D=D
        self.h=h
    def quantity(self, pd):
        qd=np.array((self.D@pd)+self.h)
        return qd
class Supply:
    ### e 拮据
    def __init__(self, C, e):
        self.C=C
        self.e=e
    def quantity(self, ps):
        qs=np.array((self.C@ps)+self.e)
        ### ps is a scalar  但是透過broadcasting  ps 可以變成一格2維array
        return qs 
class Market:
    ####instaces are demand and supply  
    def __init__(self, demand, supply):
        self.demand=demand
        self.supply=supply
    def price(self):
        pe=inv(self.supply.C-self.demand.D)@(self.demand.h-self.supply.e)
        return pe
    def quantity(self):
        qe=self.demand.D@self.price()+self.demand.h
        return qe
    def equilibrium(self):
        pe=self.price()
        qe=self.quantity()
        return pe, qe


D=np.array([
    [-5,-5],
    [-1,-10]
])
h=np.array([
    [100],
    [50]
])
C=np.array([
    [10,5],
    [5,10]
])
e=np.array([
    [0],
    [0]
])

demand = Demand(D, h)
supply = Supply(C, e)
market = Market(demand, supply)


market.equilibrium()

(array([[6.25 ],
        [0.625]]),
 array([[65.625],
        [37.5  ]]))

In [3]:

D=np.array([
    [-5,-5],
    [-1,-10]
])
D.shape 

(2, 2)

In [4]:
import numpy as np
np.random.seed(2023)

epsilon = np.random.normal(0, 0.2, (10,2))

epsilon

array([[ 0.14233471, -0.06489699],
       [-0.20037413,  0.04725016],
       [-0.02043197, -0.22825853],
       [ 0.53088145,  0.28812104],
       [ 0.01978045, -0.62430643],
       [-0.21530433, -0.06513639],
       [-0.20709958, -0.08526408],
       [-0.20587228, -0.10435484],
       [-0.08455151, -0.01984883],
       [-0.2760516 ,  0.06038056]])

In [ ]:
#Design a supply_shock method so that the following code can:

#compute equilibrium outcome of each epsilon[i]; and
#remember the process

market.supply_shocks(epsilon)

In [11]:
import numpy as np
from numpy.linalg import inv

class Demand:
    def __init__(self, D, h):
        self.D = D
        self.h = h
        
    def quantity(self, pd):
        qd = np.array((self.D @ pd) + self.h)
        return qd

class Supply:
    def __init__(self, C, e):
        self.C = C
        self.e = e
        
    def quantity(self, ps):
        qs = np.array((self.C @ ps) + self.e)
        return qs 

class Market:
    def __init__(self, demand, supply,epsilon_list):
        self.demand = demand
        self.supply = supply
        self.epsilon_list = np.array([])
        self.pe_history = []
        self.qe_history = []
        
    def price(self):
        C = self.supply.C   
        D = self.demand.D   
        h = self.demand.h   
        e = self.supply.e   
        pe = inv(C - D) @ (h - e)
        return pe
    
    def quantity(self):
        C = self.supply.C   
        D = self.demand.D   
        pe = self.price()
        qe = D @ pe + self.demand.h
        return qe
    
    def equilibrium(self):
        pe = self.price()
        qe = self.quantity()
        return pe, qe
    
    def supply_shock(self, epsilon_list):
        for epsilon in epsilon_list:
            self.supply.e += epsilon
            pe, qe = self.equilibrium()
            self.pe_history.append(pe)
            self.qe_history.append(qe)

In [6]:
D=np.array([
    [-5,-5],
    [-1,-10]
])
h=np.array([
    [100],
    [50]
])
C=np.array([
    [10,5],
    [5,10]
])
e=np.array([
    [0],
    [0]
])

In [14]:
demand = Demand(D, h)
supply = Supply(C, e)
market = Market(demand, supply)
market.equilibrium()
market.supply_shock(20)

TypeError: 'int' object is not iterable

In [8]:
a=range(10)
list(a) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### for loop idea
- `for i in a `
- `i ` is iterate, any iterate object can be used in for loop  

In [19]:
a=range(10)
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
iterator_a=a.__iter__() 
iterator_a

In [10]:
import numpy as np
from numpy.linalg import inv
class Demand:
    def __init__(self, D, h):
        self.D=D
        self.h=h
    def quantity(self, pd):
        qd=np.array((self.D@pd)+self.h)
        return qd
class Supply:
    def __init__(self, C, e):
        self.C=C
        self.e=e
    def quantity(self, ps):
        qs=np.array((self.C@ps)+self.e)
        return qs
class Market:
    def __init__(self, demand, supply, epsilon):
        self.demand = demand
        self.supply = supply
        self.memory = np.array([])
        self.ep = epsilon
    def price(self):
        pe=inv(self.supply.C-self.demand.D)@(self.demand.h-self.supply.e)
        return pe
    def quantity(self):
        qe=self.demand.D@self.price()+self.demand.h
        return qe
    def equilibrium(self):
        pe=self.price()
        qe=self.quantity()
        return pe, qe

    def supply_shocks(self, eps):
        for i in range(10):
            E = np.array([
                [eps[i, 0]],
                [eps[i, 1]]
            ])
            pe = inv(self.supply.C - self.demand.D) @ (self.demand.h - (self.supply.e + E))
            qe = self.demand.D @ pe + self.demand.h
            self.memory = np.append(self.memory, [pe, qe])
        return pe, qe

D=np.array([
    [-10,-5],
    [-1,-10]
])
h=np.array([
    [100],
    [50]
])
C=np.array([
    [10,5],
    [5,10]
])
e=np.array([
    [0],
    [0]
])
np.random.seed(2023)

epsilon = np.random.normal(0, 0.2, (10, 2))

demand = Demand(D, h)
supply = Supply(C, e)
market = Market(demand, supply, epsilon= epsilon)
print(market.equilibrium() )
market.supply_shocks(eps=market.ep)

print(market.memory)

(array([[4.41176471],
       [1.17647059]]), array([[50.        ],
       [33.82352941]]))
[ 4.40148334  1.18279985 50.07116735 33.77051819  4.42494113  1.17015515
 49.89981294 33.87350734  4.4062531   1.189537   49.98978402 33.69837694
  4.38901053  1.16889079 50.26544073 33.92208159  4.3922392   1.21354356
 50.00989023 33.47232518  4.42251389  1.17650265 49.89234784 33.81245958
  4.42143927  1.17783142 49.89645021 33.8002465   4.42080558  1.17897607
 49.89706386 33.78943374  4.41615454  1.17614608 49.95772424 33.82238465
  4.42977893  1.16804729 49.8619742  33.88974815]


In [2]:
import numpy as np  
import scipy.stats as stats 

epsilon = np.random.normal(0, 0.2, (10, 2))
epsilon

array([[-0.13962346, -0.16954851],
       [ 0.30913   ,  0.04407933],
       [-0.11535947,  0.00322026],
       [ 0.28006117,  0.0252311 ],
       [-0.06910258, -0.20382324],
       [-0.14805749, -0.412729  ],
       [-0.13556596, -0.07830878],
       [ 0.02107008, -0.08259143],
       [ 0.11506609, -0.24371359],
       [ 0.11311672, -0.1006014 ]])

In [ ]:
import numpy as np
from numpy.linalg import inv

class Demand:
    def __init__(self, D, h):
        self.D = D
        self.h = h
        
    def quantity(self, pd):
        qd = np.array((self.D @ pd) + self.h)
        return qd

class Supply:
    def __init__(self, C, e):
        self.C = C
        self.e = e
        
    def quantity(self, ps):
        qs = np.array((self.C @ ps) + self.e)
        return qs 

class Market:
    def __init__(self, demand, supply):
        self.demand = demand
        self.supply = supply
        self.pe_history = []
        self.qe_history = []
        
    def price(self):
        C = self.supply.C   
        D = self.demand.D   
        h = self.demand.h   
        e = self.supply.e   
        pe = inv(C - D) @ (h - e)
        return pe
    
    def quantity(self):
        C = self.supply.C   
        D = self.demand.D   
        pe = self.price()
        qe = D @ pe + self.demand.h
        return qe
    
    def equilibrium(self):
        pe = self.price()
        qe = self.quantity()
        return pe, qe
    
    def supply_shock(self, epsilon_list):
        for epsilon in epsilon_list:
            self.supply.e += epsilon
            pe, qe = self.equilibrium()
            self.pe_history.append(pe)
            self.qe_history.append(qe)

In [ ]:
# 定義需求曲線和供給曲線
D = np.array([[10, -2], [8, -4], ])
h = np.array([50, 40])
C = np.array([[2, 1], [4, 2], ])
e = np.array([0, 0])

demand = Demand(D, h)
supply = Supply(C, e)

# 創建市場對象
market = Market(demand, supply, [])

# 計算市場均衡
pe, qe = market.equilibrium()
print("Equilibrium price:", pe)
print("Equilibrium quantity:", qe)

# 模擬供給曲線的變化
epsilon_list = np.array([[0.1, 0], [0, 0.2]])
market.supply_shock(epsilon_list)

# 繪製均衡價格和數量的歷史記錄
import matplotlib.pyplot as plt
plt.plot(market.pe_history, label="Price")
plt.plot(market.qe_history, label="Quantity")
plt.legend()
plt.show()

In [21]:
import numpy as np
from numpy.linalg import inv

class Demand:
    def __init__(self, D, h):
        self.D = D
        self.h = h
        
    def quantity(self, pd):
        qd = np.array((self.D @ pd) + self.h)
        return qd

class Supply:
    def __init__(self, C, e):
        self.C = C
        self.e = e
        
    def quantity(self, ps):
        qs = np.array((self.C @ ps) + self.e)
        return qs 

class Market:
    def __init__(self, demand, supply, epsilon_list=None):
        self.demand = demand
        self.supply = supply
        self.epsilon_list = epsilon_list if epsilon_list is not None else np.array([])
        self.pe_history = []
        self.qe_history = []
        
    def price(self):
        C = self.supply.C   
        D = self.demand.D   
        h = self.demand.h   
        e = self.supply.e   
        pe = inv(C - D) @ (h - e)
        return pe
    
    def quantity(self):
        C = self.supply.C   
        D = self.demand.D   
        pe = self.price()
        qe = D @ pe + self.demand.h
        return qe
    
    def equilibrium(self):
        pe = self.price()
        qe = self.quantity()
        return pe, qe
    
    def supply_shock(self, epsilon_list):
        for epsilon in epsilon_list:
            self.supply.e = self.supply.e.astype(float)
            self.supply.e += epsilon.astype(float)
            pe, qe = self.equilibrium()
            self.pe_history.append(pe)
            self.qe_history.append(qe)

# 定義需求曲線和供給曲線
D = np.array([[10, -2], [8, -4]])
h = np.array([50, 40])
C = np.array([[2, 1], [4, 2]])
e = np.array([0, 0])

demand = Demand(D, h)
supply = Supply(C, e)

# 創建市場對象
market = Market(demand, supply)

# 計算市場均衡
pe, qe = market.equilibrium()
print("Equilibrium price:", pe)
print("Equilibrium quantity:", qe)

# 模擬供給曲線的變化
epsilon_list = np.array([[1, 30], [0, 2], [-1, 0]])
market.supply_shock(epsilon_list)

# 繪製均衡價格和數量的歷史記錄


Equilibrium price: [-5.          3.33333333]
Equilibrium quantity: [ -6.66666667 -13.33333333]
