In [2]:
import numpy as np
from numpy.linalg import inv
class Demand:
    def __init__(self, D, h):
        self.D=D
        self.h=h
    def quantity(self, pd):
        qd=np.array((self.D@pd)+self.h)
        return qd
class Supply:
    ### e 拮据
    def __init__(self, C, e):
        self.C=C
        self.e=e
    def quantity(self, ps):
        qs=np.array((self.C@ps)+self.e)
        ### ps is a scalar  但是透過broadcasting  ps 可以變成一格2維array
        return qs 
class Market:
    ####instaces are demand and supply  
    def __init__(self, demand, supply):
        self.demand=demand
        self.supply=supply
    def price(self):
        pe=inv(self.supply.C-self.demand.D)@(self.demand.h-self.supply.e)
        return pe
    def quantity(self):
        qe=self.demand.D@self.price()+self.demand.h
        return qe
    def equilibrium(self):
        pe=self.price()
        qe=self.quantity()
        return pe, qe


D=np.array([
    [-5,-5],
    [-1,-10]
])
h=np.array([
    [100],
    [50]
])
C=np.array([
    [10,5],
    [5,10]
])
e=np.array([
    [0],
    [0]
])

demand = Demand(D, h)
supply = Supply(C, e)
market = Market(demand, supply)


market.equilibrium()

(array([[6.25 ],
        [0.625]]),
 array([[65.625],
        [37.5  ]]))

In [3]:

D=np.array([
    [-5,-5],
    [-1,-10]
])
D.shape 

(2, 2)

In [4]:
import numpy as np
np.random.seed(2023)

epsilon = np.random.normal(0, 0.2, (10,2))

epsilon

array([[ 0.14233471, -0.06489699],
       [-0.20037413,  0.04725016],
       [-0.02043197, -0.22825853],
       [ 0.53088145,  0.28812104],
       [ 0.01978045, -0.62430643],
       [-0.21530433, -0.06513639],
       [-0.20709958, -0.08526408],
       [-0.20587228, -0.10435484],
       [-0.08455151, -0.01984883],
       [-0.2760516 ,  0.06038056]])

In [ ]:
#Design a supply_shock method so that the following code can:

#compute equilibrium outcome of each epsilon[i]; and
#remember the process

market.supply_shocks(epsilon)

In [11]:
import numpy as np
from numpy.linalg import inv

class Demand:
    def __init__(self, D, h):
        self.D = D
        self.h = h
        
    def quantity(self, pd):
        qd = np.array((self.D @ pd) + self.h)
        return qd

class Supply:
    def __init__(self, C, e):
        self.C = C
        self.e = e
        
    def quantity(self, ps):
        qs = np.array((self.C @ ps) + self.e)
        return qs 

class Market:
    def __init__(self, demand, supply):
        self.demand = demand
        self.supply = supply
        self.pe_history = []
        self.qe_history = []
        
    def price(self):
        C = self.supply.C   
        D = self.demand.D   
        h = self.demand.h   
        e = self.supply.e   
        pe = inv(C - D) @ (h - e)
        return pe
    
    def quantity(self):
        C = self.supply.C   
        D = self.demand.D   
        pe = self.price()
        qe = D @ pe + self.demand.h
        return qe
    
    def equilibrium(self):
        pe = self.price()
        qe = self.quantity()
        return pe, qe
    
    def supply_shock(self, epsilon_list):
        for epsilon in epsilon_list:
            self.supply.e += epsilon
            pe, qe = self.equilibrium()
            self.pe_history.append(pe)
            self.qe_history.append(qe)

In [6]:
D=np.array([
    [-5,-5],
    [-1,-10]
])
h=np.array([
    [100],
    [50]
])
C=np.array([
    [10,5],
    [5,10]
])
e=np.array([
    [0],
    [0]
])

In [14]:
demand = Demand(D, h)
supply = Supply(C, e)
market = Market(demand, supply)
market.equilibrium()
market.supply_shock(20)

TypeError: 'int' object is not iterable

In [8]:
a=range(10)
list(a) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### for loop idea
- `for i in a `
- `i ` is iterate, any iterate object can be used in for loop  

In [19]:
a=range(10)
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
iterator_a=a.__iter__() 
iterator_a

In [21]:
a._next_()

AttributeError: 'range' object has no attribute '_next_'